services:

    darsyn_dogfood.data_strategy.json:
        class: Darsyn\Bundle\DogfoodBundle\DataStrategy\Json

    darsyn_dogfood.proxy:
        class: Darsyn\Bundle\DogfoodBundle\Proxy\Proxy
        arguments:
            - @http_kernel
            - @request_stack
            - @router
            - @event_dispatcher
            - @logger
        calls:
            - [ setDataStrategy, [ @darsyn_dogfood.data_strategy.json ]]
